#! /bin/bash
set -e

moc-gather-info ()
{
	local key val
	while read -r key val ; do
		eval "Moc${key%:}='${val}'"
	done < <( mocp --info )
}

moc-gather-info

case ${MocState} in
	PAUSE) stat=Paused ;;
	PLAY ) stat=Playing ;;
	*    ) exit 0 ;;
esac

exec notify-send              \
	--expire-time=5000          \
	--icon=gnome-volume-control \
	"${stat}: ${MocSongTitle}"  \
	"From <b>${MocAlbum}</b> by <b>${MocArtist}</b>"
