#!/usr/bin/env bash

case "$1" in

	scratchpad) 		
        entry="kitty -t scratchpad" 		
        ;;
	FM) 		
        entry="kitty -t kkk -e /home/dmne/.local/bin/scratchnnn.sh"		
        ;;
    Mail)
        entry="alacritty -t Mail -e neomutt"
        ;;
    Music)
        entry="alacritty -t Music -e ncmpcpp"
        ;;
    Todo)
        entry="alacritty -t Todo -e schedule.sh"
        ;;
    launch)
        entry="alacritty -t launch -e launch.sh"
esac

xdotool search --onlyvisible --name "$1" windowunmap \
    || xdotool search --name "$1" windowmap \
    || $entry &
